apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:fXQi7w8giGIdKPEaLVr0x+fZwkOM9/HAMeJ6kTNPro2fp7XN,iv:8mJCvoR/URQRJgAk/iu21bcxA6owJAlg3Ad90XRxAhA=,tag:9U93wh5ankwm3z1faH20OQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:vw9EioCq7GNBOnULYTBQ9kzmP3KLDVnJ//2E0StEkYR00Mq/88PdN6Xdn78uc0Rj419oJbB5ZH933eQObfgrpvQglyUjASoaohK3os40JG7aF8DE0/Z1k3MzYedbzu6+J5a0DbwV7Fv/T8hyhfWDeb4epbXIPx2LfdSzJzDX63un9UV2AaFDP/lEdzMKRTQyH/DIdr1y8UVgOckYOclQmD31Jaq6MNLNZa6crJcxlA==,iv:Um+DpFvAMHvYS3EYVlcPIImMnzjHAy44HsZPjzl1Qwc=,tag:Pb9g5SwW6V5IBcf8VyXbEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mhnr8fvmul5cuwxxw5yfe9g9ztqga60f4c3zu5e4lrymfvwahegqyfqkp9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RTY2czFRVVFxcU0xZU9D
            cWM0bmF1bXJVMTFUU0haL0hXbjdaMTNlczFRCjA4VDhVTlZhVW03Vml4MURLUEZX
            dTd0T0YreTRVZk1vNUE1akZWenVSdFUKLS0tIFc2WjdSUmlYWDFseGJ5NnpPTHhB
            aWhJR0J0UVhBeVh1bHdSekNsZ0NzOEkKftk5Rogwa+zjHpSYTg31Ab/WlKbWpntk
            Ic+7rYVq+2ryxHJ1nJmdvzawZI/KmmpuAgmyLpTIspYtph5dNGvXjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-06T07:23:27Z"
    mac: ENC[AES256_GCM,data:v1RyeNy0cqu88ZSYFnT5gbUwZ70E502zko4DiStDcAPfjZVcnIz7f8QS2XaMNwa+lVXEj1vLpwdsPBUtSHp6JBDdaJdXWaJiyN9YjwnyOnWZy9cgaVTw9jgARE/tIG04cppcbMZ1e3nhnupS4UVqUQRp6O8KeYt5SRSrx/uGAzM=,iv:JQJvQ1+e+bKXCocGcTssW2knMy12zvCTtreAWg3zHu4=,tag:YmUJcpVUV93q9PwEq0FlVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
